services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /mnt/external_ssd/media_server/plex/config:/config
      - /mnt/external_ssd/media_server/series:/tv
      - /mnt/external_ssd/media_server/movies:/movies
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/external_ssd/media_server/radarr:/config
      - /mnt/external_ssd/media_server/movies:/movies #optional
      - /mnt/external_ssd/media_server/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/external_ssd/media_server/sonarr:/config
      - /mnt/external_ssd/media_server/series:/tv #optional
      - /mnt/external_ssd/media_server/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
