services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${MEDIA_SERVER_DIR}/plex/config:/config
      - ${MEDIA_SERVER_DIR}/series:/tv
      - ${MEDIA_SERVER_DIR}/movies:/movies
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_DIR}/radarr:/config
      - ${MEDIA_SERVER_DIR}/movies:/movies #optional
      - ${MEDIA_SERVER_DIR}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_DIR}/sonarr:/config
      - ${MEDIA_SERVER_DIR}/series:/tv #optional
      - ${MEDIA_SERVER_DIR}/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
