networks:
  default:
    name: media_server

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${MEDIA_SERVER_DIR}/plex/config:/config
      - ${MEDIA_SERVER_DIR}/data/series:/tv
      - ${MEDIA_SERVER_DIR}/data/movies:/movies
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_DIR}/radarr:/config
      - ${MEDIA_SERVER_DIR}/data/movies:/movies #optional
      - ${MEDIA_SERVER_DIR}/data/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_DIR}/sonarr:/config
      - ${MEDIA_SERVER_DIR}/data/series:/tv #optional
      - ${MEDIA_SERVER_DIR}/data/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped